### ISSUE TITLE
Time calculation wrong if end time is in the future.

### ISSUE THREAD

**Issue by deisi** [traggo/server#105]
**Describe the bug**
If you define the end time of a task in the future, the time calculation is wrong. See screenshot for prove

**To Reproduce**
I just observed this wrong calculation while it was about 16:20 at that day. So I setted the end time to something in the future at that point. Thus I assume this is what is causing the issue.
1. Start task
2. Define stop time in future
3. Take a look at how current time effects calculated

**Expected behavior**
Well current time should be irrelevant for task duration at that point.

**Screenshots**
![time_calc_wrong](https://user-images.githubusercontent.com/5436980/148791452-bb650b32-f963-4f78-9754-3ba84a8e935c.png)

**Additional context**
I don't think there is anything special but I use a docker container and run version 0.2.1. I

**Comment by jmattheis** [comment]
What exactly is wrong? 13 to 17 are 4 hours.

**Comment by deisi** [comment]
Ups, I did not look at this correctly for some reason I was reading 33 min and not 33s. 
Never mind
