### ISSUE TITLE
Traggo can't count

### ISSUE THREAD

**Issue by jinks** [traggo/server#110]
**Describe the bug**
When correcting a timespan that was originally created via tracker you have no ability to change the seconds that have been counted, but they sill factor into the time calculation.

**Expected behavior**
The time in the screenshot below should clearly be 1h 45m, not 44m. I have no way of changing this off-by-one-minute behavior.
Changing either time changes the amount of time, but it's always off, since the seconds in start and end don't ever change.

**Screenshots**
![screenshot_2022-02-16-203118](https://user-images.githubusercontent.com/285602/154341907-c588ecdf-7adc-4810-a84d-9f0d52a4f9d3.png)

**Suggested change**
When changing the time interval via the date selector it should set seconds to "00" since you have no way of entering a value.

**Additional**
In my use case I need to track time in 15 minute intervals, so every timespan should be a multiple of 0.25 hours. It would be nice if one could pre-configure such fixed intervals.

**Comment by jmattheis** [comment]
I'm open to accept PRs for this.

**Comment by MaximilianSoerenPollak** [comment]
@jmattheis  If you still search for someone to take care of this let me know I could take this on and try a PR.

**Comment by jmattheis** [comment]
@MaximilianSoerenPollak Yeah, feel free to work on this ticket.

**Comment by MaximilianSoerenPollak** [comment]
Tried my hand at it, please see #174 for the Details. Let me know if there is anything to fix in the PR.
