### ISSUE TITLE
Traggo application not working

### ISSUE THREAD

**Issue by reddy1993** [traggo/server#113]
**Have you read the documentation?**
- [yes ]  but it does not include related information regarding my question.
- [ yes]  but the steps described in the documentation do not work on my machine.
- [yes ] but I am having difficulty understanding it and want clarification.

**You are setting up traggo in**
- [ ] Docker
- [ yes] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Traggo is not running permanently when I close my putty session. 
when I ping the installed server publicip:3030, browser returns [ **This site can’t be reached** ] message.
chmod +x traggo-server-0.0.9-linux-amd64
After executing above command I am unable to see traggo configuration files in my ubuntu machine

**Comment by jmattheis** [comment]
When you close your putty session, then all running processes in the sessions will be closed, this includes traggo if you start it in putty. You could create a systemd server or do something like described in here https://askubuntu.com/questions/8653/how-to-keep-processes-running-after-ending-ssh-session.
