### ISSUE TITLE
Using The App with Nginx Proxy Manager

### ISSUE THREAD

**Issue by Shahin-rmz** [traggo/server#123]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up traggo in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
A clear and concise description of what the question is.
I can rund and reach traggo locally, but have problem see

**Any errors, logs, or other information that might help us identify your problem**
Don't know exacly to check errors
Ex: `docker-compose.yml`, `nginx.conf`, browser requests, etc.

Hello, 
I installed the app, and it works smoothly.
The only catch is, I can not connect the app to a subdomain through nginx proxy manager.
I have already tried to put this part, on Advanced section of Nginx Proxy manager but it didn't work.
![image](https://user-images.githubusercontent.com/32805117/174683112-804c9a06-23e1-44f9-9cde-f41de8359281.png)

Any idea what is my problem? I get Error 502.
Port is open and config is like other selfhosted services.

**Comment by Shahin-rmz** [comment]
Hello, any tips ism wellcome.
I'm a bit stock and don't know what is the problem actually.

**Comment by jmattheis** [comment]
Can you access traggo directly via localhost:3030? Add all configuration related to traggo, docker-compose.yml etc. does traggo output any logs? You can have a look at this with `docker logs`.

**Comment by Shahin-rmz** [comment]
yes, it works perfectly localhost.
Just when I add the configs from [here](https://traggo.net/reverse-proxy/) to my Nginx P. M. with this config 
![image](https://user-images.githubusercontent.com/32805117/175106501-5fae21e8-d1ad-4f8d-81c4-dc80682dfdab.png)

it doesn't work.

**Comment by jmattheis** [comment]
If traggo is working, then there is something wrong with your reverse proxy setup. Traggo isn't the cause for this. Your proxy manager most likely cannot access traggo via localhost:3030, because it runs in a different container.

**Comment by Shahin-rmz** [comment]
yes, there is no problem with traggo itself.
and yes it is different container.
What is the solution? I'm clueless a bit, and don't know even what to search.

**Comment by Shahin-rmz** [comment]
> Do you have other services that use the nginx proxy manager? 

yes

> then you can use the name of the docker container instead of localhost.

I think now I get what is problem. I had problems to connect networks to my Nginx Proxy Manager.
lack of Devops knowledge.
I will try to connect them via network, and write the name (or ip) of traggo inside the configs.
Thanks.

**Comment by khraibani-h** [comment]
it should be as following: 
scheme: http
forward hostname: <traggo- whatever docker name>/IP 
forward port: 3030
