### ISSUE TITLE
Issue with static dates

### ISSUE THREAD

**Issue by FromDarkHell** [traggo/server#124]
**Describe the bug**
You're unable to create a dashboard entry with a consistent date for a relative time. 

**To Reproduce**
1. In a custom dashboard, create a new entry
2. Set the `To` or `From` to a static date matching the [`YYYY-MM-DD HH:mm`](https://github.com/traggo/server/blob/master/ui/src/utils/time.ts#L136) format for example `2022-03-01 00:00`
3. Hit `Preview` (Hitting `Save` will just do nothing as the GraphQL query fails)

**Expected behavior**
It should create a new entry showing from `2022-03-01 00:00` to `now` for example.

**Screenshots**
![image](https://user-images.githubusercontent.com/9018764/175217596-3dec2acd-d946-4512-8963-17f83a008246.png)
![image](https://user-images.githubusercontent.com/9018764/175217608-27b2e3d2-18e5-4931-ae68-82e636556e20.png)

**Comment by jmattheis** [comment]
Duplicates #101
