### ISSUE TITLE
[yunohost] Cannot log in with generic or defined credentials

### ISSUE THREAD

**Issue by paczesik** [traggo/server#128]
After installation of Traggo on Yunohost cannot log in to the system. Admin/admin or defined during installation credentials do not work.

1. Install via Yunohost WebUI
2. Navigate to the app address
3. Insert log in credentials
4. See error: "Login failed: username/password combination does not exist"

**Screenshots**
![obraz](https://user-images.githubusercontent.com/115451599/201891042-4f950825-b79e-481e-a5e8-075af0217a3c.png)

**Comment by jmattheis** [comment]
The default user will be created on the first startup, if you've changed the default password afterwards it won't be changed. You most likely just typed in a wrong user or password. You can try deleting the traggo database, to re-create the default user on traggo restart.

**Comment by paczesik** [comment]
Yeah tried every possible option, not working still. How do I delete the database and recreate it?

**Comment by isotipu** [comment]
Hi, I ran in the same issue. deleting the traggo database didn't bring any ease. even after a restart. The problem persists. Any other ideas how this can be fixed? I'd really like to try out traggo.

**Comment by davinian** [comment]
Same problem, new install of Traggo and when I try and login I get "Login failed: username/password combination does not exist"

Looking in .env I can see default Username/Password but this doesn't work!

Anyone got any suggestions?

**Comment by davinian** [comment]
@jmattheis yes I did but made no difference. But! I completely removed Traggo and installed again and this time it seemed to work - so not sure if a glitch when first installing via Yunohost!? The strange thing was I could see the un/pw in the .env file but that didn't work.

Anyway, it's working now and I'll have a play for a few days and see if it fits my workflow.
