### ISSUE TITLE
There is something wrong with Docker images published

### ISSUE THREAD

**Issue by ngosang** [traggo/server#129]
**Describe the bug**
There is something wrong with Docker images published in https://hub.docker.com/r/traggo/server/tags
No matter what the architecture is, in Dockerhub all are published as "linux/amd64". I'm not saying they are not working, just it's confusing.
![image](https://user-images.githubusercontent.com/10577978/208242467-4a3ae5b0-0f5b-47ce-87ec-18bac5cd009a.png)

If look any other image, the architectures are right. For example https://hub.docker.com/_/python/tags?page=1&name=3.11.1
![image](https://user-images.githubusercontent.com/10577978/208242522-09a1d3ea-a526-448a-bc83-269c254ddf8f.png)

**Comment by jmattheis** [comment]
Yeah, you're right. The version 0.2.1 looks okay. So, docker probably changed something on the API that is used by traggo.

**Comment by jmattheis** [comment]
Fixed with 0.4.1.
