### ISSUE TITLE
Request for Docker arm64/v8 image

### ISSUE THREAD

**Issue by martinge17** [traggo/server#132]
**Is your feature request related to a problem? Please describe.**
It's not possible to run traggo server on devices like Raspberry Pi 4 with 64bits OS.

**Describe the solution you'd like**
Support for arm64/v8.

**Comment by jmattheis** [comment]
have you tried `traggo/server:arm64-0.2.3`?

**Comment by martinge17** [comment]
Yes, but I get this error:

> traggo The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s

I think it's related with #129

**Comment by jmattheis** [comment]
Yes, it's related, but you should still be able to run the image, see https://stackoverflow.com/q/72152446/4244993

I'll close this issue in favor of #129

**Comment by martinge17** [comment]
Yes, it worked.
Thank you !!!
