### ISSUE TITLE
Web app manifest false URL

### ISSUE THREAD

**Issue by Bubbu0129** [traggo/server#136]
**Describe the bug**
#94 added [manifest.json](https://github.com/traggo/server/blob/master/ui/public/manifest.json), but `start_url` and `scope` are both set to `/`, the root of the site. If traggo is configured to run in a sub-directory, mobile devices won't install the shortcut properly.

Setting
``` json
"start_url": "./"
"scope": "."
```
will solve the bug.

**Comment by jmattheis** [comment]
I'll change both to `./`
