### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Skeen** [traggo/server#138]
**Is your feature request related to a problem? Please describe.**
The currently released version to Dockerhub 0.2.3 is 10 months old, and several changes has enter the source-code since then.

**Describe the solution you'd like**
Release a new version.

**Describe alternatives you've considered**
Building and releasing unofficially.

**Additional context**
I'm looking for the "impersonate" change to be released in particular.

**Comment by jmattheis** [comment]
The impersonate feature is currently only implemented in the backend and isn't usable inside the UI.

**Comment by Skeen** [comment]
I am aware, I only need it in the API for integrations
