### ISSUE TITLE
Time entry shift and calendar display issues in Iran timezone after daylight saving removal

### ISSUE THREAD

**Issue by MkSafavi** [traggo/server#147]
**Describe the bug**
recently Iran updated the timezone and removed summer day light saving.
when editing an entry in Traggo it would automatically +1 the hour. just to make sure I reproduced it with a new container as well. It only happened with Iran timezone.

**reproduce editing bug**
set timezone to Iran (Asia/Tehran)
add an entry from 14:30  to 14:45. 
![image](https://github.com/traggo/server/assets/50653293/276e0733-8871-4507-b964-94a697c830bc)
change 14:30 to 12:30 it would enter 13:30.
![image](https://github.com/traggo/server/assets/50653293/7214b77e-47be-4dbe-b7a7-b29f62f35246)

**more cases**
New entries are shifted by one hour: (the start time should be 12:49)
![image](https://github.com/traggo/server/assets/50653293/44c8d88f-064f-40b2-a155-1928366aa912)

The calendar view is broken. the entries are showing on the correct time (based on the left side timescale) but the entry time itself is not correct.
![image](https://github.com/traggo/server/assets/50653293/b6b62b51-7355-47b5-91e9-fac64446835b)

**Comment by jmattheis** [comment]
Good catch, traggo bundles its own timezone database and the 0.3.0 version still has the outdated daylight savings time.

**Comment by jmattheis** [comment]
Could you try out [v0.4.4](https://github.com/traggo/server/releases/tag/v0.4.4)

**Comment by MkSafavi** [comment]
Awesome. It's fixed.
Thanks for looking into it.
