### ISSUE TITLE
Traggo does not build

### ISSUE THREAD

**Issue by Vagahbond** [traggo/server#152]
**Describe the bug**
When trying to build following your guide, it does not work, whether it is on master or on the latest release tag.

**To Reproduce**
1. Clone the repo 
2. `make generate`

**Expected behavior**
The above command works and we can go on and compile.

**Screenshots**
```
❯ make generate                                                          via 🐹 v1.20.8 via ❄️  impure (shell) 
go run hack/gqlgen/gqlgen.go
go: github.com/99designs/gqlgen@v0.9.0 requires
	sourcegraph.com/sourcegraph/appdash-data@v0.0.0-20151005221446-73f23eafcf67: unrecognized import path "sourcegraph.com/sourcegraph/appdash-data": reading https://sourcegraph.com/sourcegraph/appdash-data?go-get=1: 404 Not Found
go: github.com/99designs/gqlgen@v0.9.0 requires
	sourcegraph.com/sourcegraph/appdash-data@v0.0.0-20151005221446-73f23eafcf67: unrecognized import path "sourcegraph.com/sourcegraph/appdash-data": reading https://sourcegraph.com/sourcegraph/appdash-data?go-get=1: 404 Not Found
make: *** [Makefile:30: generate-go] Error 1
```

**Additional context**
I'm not a gopher so I'm not sure what is happening but it seems like a dependency disappeared..

**Comment by jmattheis** [comment]
Yeah, your right. I pushed new changes to master that update the dependency and fix this problem. You can build the binary with
```
make download-tools generate build-bin-local
```
the other build commands via docker doesn't work because the build image is outdated. If you have a newer nodejs version you may have to export this variable before executing the make command above.
```
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by Vagahbond** [comment]
Indeed it works! 

I tried building with docker because I was too lazy to create a nix shell,  and it worked great for me. 

Thanks for this simple but powerful tool !
