### ISSUE TITLE
Issues building Traggo v0.4.2

### ISSUE THREAD

**Issue by hulmgulm** [traggo/server#159]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up traggo in**
- [ ] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Seeing Traggo v0.4.1 being released I did the following to build my own version:

```
git clone https://github.com/traggo/server.git
cd server
export PATH=$PATH:~/go/bin
make download-tools install generate build-bin-local
```
which worked fine. Seeing 0.4.2 this morning, I did the same (yes, I did a clean clone) but now I always get this error:

```
CGO_ENABLED=1 go build -a -ldflags '-s -w -linkmode external -extldflags "-static" -X main.BuildDate=2024-03-08T05:49:13Z -X main.BuildMode=prod -X main.BuildCommit=d0674d80b8cd0b2609c4c7f29debcacfbeabdce2 -X main.BuildVersion=0.4.2' -tags 'netgo osusergo sqlite_omit_load_extension' -o ./build/traggo-server
# github.com/traggo/server/ui
ui/serve.go:25:45: undefined: http.FileServerFS
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:123303:10: warning: function may return address of local variable [-Wreturn-local-addr]
123303 |   return pNew;
       |          ^~~~
sqlite3-binding.c:123263:10: note: declared here
123263 |   Select standin;
       |          ^~~~~~~
make: *** [Makefile:63: build-bin-local] Error 2
```

Any idea how to get traggo to build again?

**Comment by jmattheis** [comment]
Are you using the latest `go version` 1.22?

**Comment by hulmgulm** [comment]
That was the issue. Although I extracted go to my home directory and set the path accordingly, there was another go in the path which matched first.
Thank you!
