### ISSUE TITLE
Anyway to import a calander and tag those entries?

### ISSUE THREAD

**Issue by staticfrost** [traggo/server#164]
Hey, is there anyway to import a ICS or a Google Calander link and have it be tagged in automatically?

**Comment by jmattheis** [comment]
No, you could script it yourself and use the graphql api to create timespans / tags.

**Comment by staticfrost** [comment]
I don't have that knowledge, is there any doco i could read to help?

**Comment by jmattheis** [comment]
Only the graphql api definition https://github.com/traggo/server/blob/master/schema.graphql there you could use `createTimeSpan` to create a timespan.
