### ISSUE TITLE
Tag Hierarchy allow for sub tags

### ISSUE THREAD

**Issue by staticfrost** [traggo/server#165]
I want to get a total time spent for each customer but I also want to track the service time and total time on specific task

I would like to be able to track at three levels each adding new totalling number.
Customer -> Service type -> Task

So total for customer view, total for customer at a specific service type and then how much was on a specific task.

**Comment by jmattheis** [comment]
You should be able to achieve this with the current system by creating separate tags for it:
```
customer:abc
service:programming
task:cde
```
now you can get stats for the customer tag and the service tags separately.
