### ISSUE TITLE
Error in duration

### ISSUE THREAD

**Issue by seb49** [traggo/server#169]
Hello,

I'm in France, it's 05:25 PM, I have an active timer launch à 1:07 PM so barely 4 hours and 20 minutes. But traggo display only 2 hours and 20 minutes

![image](https://github.com/traggo/server/assets/2581756/5338a2f1-cb7c-4e70-9a5a-278188e2140d)

**Comment by jmattheis** [comment]
Could you share your database file. You could send it to the email on my profile. This is likely due to starting and stopping the time span in different timezones, this can be due to different browser settings.

**Comment by seb49** [comment]
This is done

**Comment by seb49** [comment]
In the same way, there are 2 hours gap in this view
![image](https://github.com/traggo/server/assets/2581756/2ac9bdb5-1799-4513-bfb7-80642aea06a0)

**Comment by seb49** [comment]
Thanks for your reply

I think it's more touchy. I use graphql to create entries. But I show in database there is this field
```
start_utc
end_utc
start_user_time
end_user_time
```
but
graphql use only start and end
```
createTimeSpan(
start: Time!
end: Time
tags: [InputTimeSpanTag!]
note: String!
): TimeSpan
```

here is some entries from databases

```
sqlite> select * from time_spans where id in (377,378,379);
377|2024-05-16 08:11:31+00:00||2024-05-16 08:11:31+00:00||0|1|PYTHON
378|2024-05-16 07:18:56+00:00|2024-05-16 07:20:54+00:00|2024-05-16 09:18:56+00:00|2024-05-16 09:20:54+00:00|7200|1|
379|2024-05-16 07:27:25+00:00||2024-05-16 09:27:25+00:00||7200|1|
```

if you read "Python", entry is create with graphql, otherwise, from browser. With browser there is 2 hours gap between user_time and utc

Regards

**Comment by jmattheis** [comment]
Then you have to fix this in your script and send your timestamps with a timezone offset.

**Comment by seb49** [comment]
This is what I do to get time
`def GetCurrentDate():
    current_datetime_utc = datetime.now(timezone.utc).replace(tzinfo=pytz.UTC)
    desired_timezone = pytz.timezone('Europe/Paris') 
    current_datetime_Paris = current_datetime_utc.astimezone(desired_timezone)
    formatted_datetime_utc_plus_one = current_datetime_Paris.strftime("%Y-%m-%dT%H:%M:%SZ")
    return formatted_datetime_utc_plus_one`

But event if I remove
`desired_timezone = pytz.timezone('Europe/Paris')`

there is no logic

![image](https://github.com/traggo/server/assets/2581756/ae8fd742-0591-4698-9cc2-6926dc628b2d)

![image](https://github.com/traggo/server/assets/2581756/c24f335d-3ffd-4037-ba9d-40630487e7f9)

the good display is on the calendar

**Comment by jmattheis** [comment]
Not a python dev, but you can get the current time with a timezone which will return the right offset.
```python
def GetCurrentDate():
    tz = pytz.timezone('Europe/Paris')
    return datetime.now(tz).isoformat()
# outputs: 2024-05-21T12:06:08.996211+02:00
```
Your method outputs `2024-05-21T12:06:08Z`

**Comment by seb49** [comment]
Great, it's work thanks.
But I don't understand why the table contains more filed than graphql can use (start_utc, end_utc, start_user_time, end_user_time)
