### ISSUE TITLE
Is this project actively developed on?

### ISSUE THREAD

**Issue by b1tray3r** [traggo/server#171]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up traggo in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
It seems this project was not worked on in four months.
Will this project receive new features or bug fixes or should it be forked to live on.

Kind regards

Alex

**Comment by jmattheis** [comment]
There is no active feature development in Traggo but I'll fix security issues and critical bugs. This project is open for contributions, so you don't have to fork it to get updates into this project.
