### ISSUE TITLE
Consistent assets naming 

### ISSUE THREAD

**Issue by Flinner** [traggo/server#176]
I see that assets types and names change each release, for example:
from `zip` to `tar.gz`. this breaks some of my build systems.

I greatly thank you for this project, and I don't feel entitled to anything, but please can we have consistant naming? I would be very grateful. thanks!

in v0.3.0
```
traggo-server-0.3.0-linux-386.zip
traggo-server-0.3.0-linux-amd64.zip
traggo-server-0.3.0-linux-arm-7.zip
traggo-server-0.3.0-linux-arm64.zip
traggo-server-0.3.0-linux-ppc64le.zip
traggo-server-0.3.0-linux-s390x.zip
traggo-server-0.3.0-windows-386.exe.zip
traggo-server-0.3.0-windows-amd64.exe.zip

```

in v0.4.5

```
traggo_0.4.5_linux_amd64.tar.gz
traggo_0.4.5_linux_arm64.tar.gz
traggo_0.4.5_linux_armv7.tar.gz
traggo_0.4.5_linux_i386.tar.gz
traggo_0.4.5_windows_amd64.zip
```

**Comment by jmattheis** [comment]
Traggo migrated to goreleaser, and this changed the format. Probably could've been done backwards compatible but now it's to late and changing it again would be unnecessary.

**Comment by Flinner** [comment]
Thanks for traggo @jmattheis , I really admire your software skills and appreciate your hordwork. 

All the best
