### ISSUE TITLE
Want to put a past date in activity

### ISSUE THREAD

**Issue by ghmonk** [traggo/server#191]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up traggo in**
- [ ] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
A clear and concise description of what the question is.

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, browser requests, etc.

I want to put an activity in the list view with a date from two days ago but the software only allows me to put today’s date.  What am I doing wrong ?

**Comment by jmattheis** [comment]
Click on the calendar icon and then click/change the date.

![image](https://github.com/user-attachments/assets/0a5f72ec-1236-42ef-9d72-c27ee43e45f7)

**Comment by ghmonk** [comment]
Hello, thank you for responding; I did that, but it doesn't work.
![image](https://github.com/user-attachments/assets/4068dee6-f913-4be4-a3fd-eb7c62a73d1b)
I changed it and pressed OK, but nothing happens.

**Comment by jmattheis** [comment]
This broke with #180.

**Comment by jmattheis** [comment]
Fixed with https://github.com/traggo/server/releases/tag/v0.5.1
