### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by icetech233** [traggo/server#192]
go: finding module for package github.com/traggo/server/generated/gqlschema
go: finding module for package github.com/traggo/server/generated/gqlmodel
go: github.com/traggo/server/auth imports
        github.com/traggo/server/generated/gqlmodel: no matching versions for query "latest"
go: github.com/traggo/server/graphql imports
        github.com/traggo/server/generated/gqlschema: no matching versions for query "latest"

**Comment by jmattheis** [comment]
https://traggo.net/dev/setup/
https://traggo.net/dev/build/
