### ISSUE TITLE
Desktop/Mobile Application

### ISSUE THREAD

**Issue by polespinasa** [traggo/server#194]
Has anyone created a desktop/mobile application to interact with the server? Something simpler than the web, just to start and stop the timers.

If not that would be great!

**Comment by jmattheis** [comment]
No, and not planned. What do you find complex about the current webui?

**Comment by polespinasa** [comment]
Not complex but not comfortable (at least for me). I would find ideal just to have a mobile/desktop app to turn on/off the timers without using the browser. As many close-source programs that do the same have.

**Comment by berilslv** [comment]
> Not complex but not comfortable (at least for me). I would find ideal just to have a mobile/desktop app to turn on/off the timers without using the browser. As many close-source programs that do the same have.

Hi mate.
create bookmark/shortcut on your phones home page, and its like app! Even my wife got used to it, we use it for tracking baby feeding! @jmattheis , thanks for developing this app! Its really cool!

**Comment by polespinasa** [comment]
That's a good option actually, good point.
