### ISSUE TITLE
PieChart based on Tag Key 

### ISSUE THREAD

**Issue by SleepiPanda** [traggo/server#73]
I want to be able to create a pie chart base on Tag Key without including Tag Value.

**Comment by jmattheis** [comment]
Could you describe a use-case for this feature?

**Comment by SleepiPanda** [comment]
Sure! I have a weekly dashboard built using ranges but at the end of the
month I would like to swap it to a monthly view to see how I'm spending my
time over a month. I currently have 6 tags set (admin, development,
customer_engagement...) And I have been using the value to put in keywords
about my tag like (admin:emails/slack, admin:interview ... Etc. When I use
the weekly range the pichart looks manageable but over a month with several
values the key and pie chart look a bit unruly.

**Comment by jmattheis** [comment]
Okay, I think you can use a different tag structure, something like: `type:admin task:email` / `type:development task:debugging`. Then you should be able to create charts based on the tag type.

**Comment by SleepiPanda** [comment]
Maybe I'm missing something is there away to apply a type without applying
a task as well? When I gave something I have to choose a type from the tags
menu and then give a value

**Comment by SleepiPanda** [comment]
Actually I see what you are saying now! I'll try that out only
