### ISSUE TITLE
[DOC] Setup instructions dont include yarn build

### ISSUE THREAD

**Issue by vabene1111** [traggo/server#75]
i am a total noob to yarn/react/go but when setting up the dev environment, following the instructions provided in the documentation i got an error that the go server cant find  `[..]ui/build/index.hmtl` (dont remember the exact message since its now fixed after the build but index.html was missing).

After running `yarn build` the file was found and everything worked as expected. Did i do something wrong or does this need to be added to the dev setup doc ?

**Comment by vabene1111** [comment]
Maybe this is related to the following error shown by the react ui server `yarn start`

```
/home/vabene/developement/go/server/ui/src/common/DateTimeSelector.tsx
TypeScript error in /home/vabene/developement/go/server/ui/src/common/DateTimeSelector.tsx(40,17):
Type '(date: moment.Moment) => void' is not assignable to type '(date: MaterialUiPickersDate, value?: string | null | undefined) => void'.
  Types of parameters 'date' and 'date' are incompatible.
    Type 'MaterialUiPickersDate' is not assignable to type 'Moment'.
      Type 'null' is not assignable to type 'Moment'.  TS2322

    38 |                 margin="none"
    39 |                 value={uglyConvertToLocalTime(selectedDate).format()}
  > 40 |                 onChange={(date: moment.Moment) => {
       |                 ^
    41 |                     if (!date.isValid()) {
    42 |                         return;
    43 |                     }
```

**Comment by jmattheis** [comment]
The error message that it can't find index.html is normal because you should use `yarn start` to access the website in dev mode.

Have you made any changes after building and running with `yarn start`? `yarn build` and `yarn start` should both fail, if there is a real error.

**Comment by vabene1111** [comment]
i have not made any changes, the error message you see above is the message shown when i visit localhost on port 3030 (after running `yarn start`). I could run `yarn build` without any issues but i will do a clean re-setup when i have time for it and try again.
