### ISSUE TITLE
Tags not saved

### ISSUE THREAD

**Issue by Evyi** [traggo/server#77]
Hi.

Nice tool!
But I face an issue here.
If I add a tag to my current logging, it is not saved.

![AC7lUfLd7t](https://user-images.githubusercontent.com/52197825/97173787-6b21b500-1791-11eb-9909-f2118b82f5be.gif)

**Comment by jmattheis** [comment]
You need to submit the tag via space or enter after you've written the value.

**Comment by Evyi** [comment]
Simple as that, thanks..
I was really sure that I tried space, but apparently no.

Great great tool so far, thanks, will help me a lot and will make my overcomplicated excel table useless!
