### ISSUE TITLE
Support for 24hours timeframe in english (calendar)

### ISSUE THREAD

**Issue by DanielNetoP** [traggo/server#78]
**Is your feature request related to a problem? Please describe.**
I have some problems when using the 12 hour frame because sometimes when changing times we select AM and then it goes to the back of the start time and it's a mess, which the German datelocale solves, because it uses the 24 hours.

**Describe the solution you'd like**
The solution would be the same as the german datelocale but without the german language (on the calendar, only the calendar changes the language, the rest of the site remains in english), if it would be possible to use 24 hours with english, or add more languages that use that 24 hour format.

**Comment by jmattheis** [comment]
Could you give a case for reproducing the problem? It would be best to fix the existing problem and not workaround it via 24h. Still a english locale with 24h format could be added.

**Comment by DanielNetoP** [comment]
This is what happened to me (in images)
I have one item at 10 am, which I stopped at 10:55 but by mistake and then I want to set the final time to 12:00
![1](https://user-images.githubusercontent.com/10155766/98574336-b66ab600-22af-11eb-8650-b89bf0ec40cc.png)

I then saw what happened:
![2](https://user-images.githubusercontent.com/10155766/98574370-bf5b8780-22af-11eb-82bb-a579cb951bd1.png)

Now I have the start time one day earlier, because as soon as I pressed the 12 the start time changed because the 12:00 am is before the start time, I hadn't had the time to press the PM button.

Then I went to update the start time again
![3](https://user-images.githubusercontent.com/10155766/98574518-ef0a8f80-22af-11eb-85ac-ddeb415c3f99.png)

And then again I went to update the end date and as soon as I click on the day the time changes again because I couldn't update the finish time to be PM instead of am
![4](https://user-images.githubusercontent.com/10155766/98574669-20835b00-22b0-11eb-858d-0e42fdfe9ee8.png)

This might happen because I'm so used at working with 24 hours instead of 12, because I don't have to be carefully about overlapping times because from 0 to 24 there's no issue, and 12 causes me this issue, might b jjust some miss usage from my side, but since so many people work with 24 hours it would be a great addition IMHO

**Comment by jmattheis** [comment]
@DanielNetoP Could you try out the newest version 0.1.2, in there a new locale setting is added (English24h).

**Comment by DanielNetoP** [comment]
That was fast 👍 
Thanks, I'm already running the 0.1.2 version and it looks awesome, 24 hours in english 😄 
Thank you very much for the awesome app, and the quick comeback, looks great!

**Comment by jmattheis** [comment]
Glad you like it!
