### ISSUE TITLE
Enhance charts with basic logic for tags and values

### ISSUE THREAD

**Issue by maxiride** [traggo/server#84]
**Is your feature request related to a problem? Please describe.**
**Feature request:** it would be handy to allow some basic logic (AND , OR) when adding tags to a dashboard element.

Given a minimal scenario where timespans are tagged with tags on the line of  "client:value", "project:value", "activity:value" it is impossible to chart out the distribution of activities of a given project. This feature request does not intend to modify the core logic of the application of the key:value approach for tags but it would involve having the possibilities to query against values as if they were keys for other elements.

**Describe the solution you'd like**
I'm brainstorming a solution on the fly here: allow users to use some basic logic in the tag selection so that timespans can be further organized and charted as:

- chosen tag value matches "x" (on the contrary all tag values except "x")
- chosen tag but not other specified tags, as of now if two timespans have both the tags "TAG1" but only one has the tag "TAG2" it is impossible to chart timespans that have _only_ "TAG1"
- match timespans that have the given tags, as of now if a chart has two tags and there is one timespan that has those tags the relevant timespan is charted two times instead of one.

**Describe alternatives you've considered**
I'm currently testing queries directly in the database.

I've also considered "moving" all the tags one level up so that timespans will be tagged as "client-name:project", "client-name:activity" but the above issues and examples would still persist, it wouldn't be possible to filter out specific projects or activities, nor match timespans that have all the tags specified or watch the activities of a given project.

**Additional context**
This feature request is aimed towards more elaborate dashboards.
Wile I could contribute on some aspects of the server side I noticed that the frontend is developed using React, and I'm a Vue guy 😄
I'm open for discussion but I think there is no need to change anything server side.

**Comment by jmattheis** [comment]
Am I understanding this correctly? You have f.ex timespans with `activity:bugfixing project:gotify`, `activity:reviewing project:traggo` now you want the chart of activities for the one specific project like `project:gotify`.

If that's the case, then the backend already support this use-case, it is just not configurable in the ui, see
https://github.com/traggo/server/blob/2f1a4d6796f91f49e9875e0bb80a5647fa1a2792/schema.graphql#L227-L234
[Test of an "include tag" definition](https://github.com/traggo/server/blob/2f1a4d6796f91f49e9875e0bb80a5647fa1a2792/statistics/summary_test.go#L160-L182)

**Comment by maxiride** [comment]
> Am I understanding this correctly?

Yes the provided API will suffice, I will play around them a bit =) Thanks for clarifying it!

**Comment by Shahin-rmz** [comment]
> If that's the case, then the backend already support this use-case, it is just not configurable in the ui, see

We have to deal with Javascript in this case right?

**Comment by jmattheis** [comment]
Depends on what you want to do.

**Comment by Shahin-rmz** [comment]
> Depends on what you want to do.

Just want to be able to see the `key`s not values.
for example: `project1:task1`, `project1:task2` and `project2:task1`
I want to see how much I time spent on project 1 and 2 in the day, and do *not* care about the tasks.
