### ISSUE TITLE
Erroneous import path\files not committed to Github?

### ISSUE THREAD

**Issue by maxiride** [traggo/server#86]
I've cloned the main branch and browsed the code (excellent work), however an import path is missing from the project and I am unable to build it locally.

https://github.com/traggo/server/blob/e90db2337b60bc5433f876fd41f28111fbf0e756/graphql/directive.go#L5

Is this intentional for some reason?

**Comment by jmattheis** [comment]
See https://traggo.net/dev/setup/#code-generation
