### ISSUE TITLE
Issues creating release build in docker container

### ISSUE THREAD

**Issue by hulmgulm** [traggo/server#90]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**Describe your problem**
I'm trying to build traggo using the docker container, but it fails with an error I cannot solve. I'm running make `build-bin-linux-amd64` as described in the documentation and this is the output:

(cd ui && yarn build)
yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command yarn upgrade
Compiled successfully.

File sizes after gzip:

  470.57 KB  build/static/js/2.ca5fdac2.chunk.js
  26.55 KB   build/static/js/main.204cee1d.chunk.js
  6.16 KB    build/static/css/2.cfded171.chunk.css
  767 B      build/static/js/runtime-main.107ac690.js
  100 B      build/static/css/main.1b706cdd.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://bit.ly/CRA-deploy

$ rimraf build/**/*.map
Done in 25.07s.
packr2
docker run --rm -v "$PWD/.:/proj" -v "`go env GOPATH`/pkg/mod/.:/go/pkg/mod:ro" -w /proj traggo/build:1.13.1-linux-amd64   go build -mod=readonly -a -installsuffix cgo -ldflags '-s -w -linkmode external -extldflags "-static" -X main.BuildDate=2021-02-27T07:12:59Z -X main.BuildMode=prod -X main.BuildCommit=0280494a9e592a4fe22bdb4a2798bfbdbc4bf240 -X main.BuildVersion=0.2.0' -tags 'netgo osusergo sqlite_omit_load_extension' -o ./build/traggo-server-0.2.0-linux-amd64 /proj
build github.com/traggo/server: cannot load home/hulmi/server/packrd: import lookup disabled by -mod=readonly
make: *** [Makefile:85: build-bin-linux-amd64] Error 1

Any idea how I can get a successful build?

Thank you!

**Comment by jmattheis** [comment]
Try installing packr2 like this
```
$ go install github.com/gobuffalo/packr/v2/packr2@v2.7.1
```
Looks like they broke the generation in a more recent version.

**Comment by hulmgulm** [comment]
Thank you,

$ go get github.com/gobuffalo/packr/v2/packr2@v2.7.1

did the trick.
