### ISSUE TITLE
Deleting start/end time causes page to crash

### ISSUE THREAD

**Issue by cmoesgaard** [traggo/server#97]
**Describe the bug**
Deleting every digit in start/end in List view, causes page to crash

**To Reproduce**
1. Go to 'List' view
2. Start a new timer
3. Select 'start' field
4. Delete all digits

**Expected behavior**
I expect to be able to delete the entire contents of the field, and type in a new start/end time

**Screenshots**
![Peek 2021-07-22 15-34](https://user-images.githubusercontent.com/1827127/126647858-3a0c1aed-fd9f-48c2-883b-36dd96b1c837.gif)

**Additional context**
Running in a docker-compose setup behind a Traefik reverse proxy, with the `traggo/server:latest` image.
'Traggo 0.2.0 @ e90db233' according to the UI

I've verified the problem with Firefox and Chromium

Browser console shows:
![image](https://user-images.githubusercontent.com/1827127/126648892-8e83ed6c-f2e6-4438-95f4-d9e728033ffe.png)

**Comment by jmattheis** [comment]
Good catch!
